- jxboot-helmfile-resources/templates/700-bucketrepo-ing.yaml
- jxboot-helmfile-resources/templates/700-chartmuseum-ing.yaml
- jxboot-helmfile-resources/templates/700-docker-ing.yaml
- jxboot-helmfile-resources/templates/700-hook-ing.yaml
- jxboot-helmfile-resources/templates/700-nexus-ing.yaml
- jxboot-helmfile-resources/values.yaml
Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>
> feat: add option to have one certificate per ingress

- jxboot-helmfile-resources/templates/upgrade-cj.yaml
- jxboot-helmfile-resources/values.yaml
> fix: add home env var

- Makefile
> fix: try fix pipeline

- jxboot-helmfile-resources/templates/jx-basic-auth-secret.yaml
- jxboot-helmfile-resources/templates/jx-basic-auth-user-password-secret.yaml
- jxboot-helmfile-resources/values.yaml
so its easy to add basic auth to ingresses if required
> fix: add basic auth secrets

- jxboot-helmfile-resources/templates/jx-basic-auth-htpasswd-secret.yaml
> fix: rename the htpasswd secret

- jxboot-helmfile-resources/values.yaml
> fix: the build controller

- jxboot-helmfile-resources/values.yaml
> fix: use the correct command

- jxboot-helmfile-resources/templates/tekton-container-registry-auth-secret.yaml
> fix: add default replicate label

- jxboot-helmfile-resources/templates/700-hook-ing.yaml
- jxboot-helmfile-resources/values.yaml
- tests/test_data/custom-env/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/custom-ingress-host/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/custom-ingress-host/values/jxRequirements.values.yaml
- tests/test_data/custom-ingress-secret/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/default/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/gitlab/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/gke-domain-bucketrepo/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/gke-domain/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/gke/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/istio/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/lighthouse-jx/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/lighthouse-tekton/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/no-envs/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/nodeport/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/private-repo/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
- tests/test_data/remote-env/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
> fix: allow custom ingress class

- jxboot-helmfile-resources/templates/repositories.yaml
> fix: lets keep scheduler for now on Environment SRs

- jxboot-helmfile-resources/templates/600-istio-gateway.yaml
- jxboot-helmfile-resources/templates/700-bucketrepo-vs.yaml
- jxboot-helmfile-resources/templates/700-chartmuseum-vs.yaml
- jxboot-helmfile-resources/templates/700-docker-vs.yaml
- jxboot-helmfile-resources/templates/700-hook-vs.yaml
- jxboot-helmfile-resources/templates/700-nexus-vs.yaml
- jxboot-helmfile-resources/values.yaml
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
> feat: allow user to provide gateway name or create gateway

- jxboot-helmfile-resources/templates/jenkins-x-docker-registry.yaml
- jxboot-helmfile-resources/values.yaml
add an easy way for configuration of global pipeline variables.
configure :
**jx-global-values.yaml**
```
jx:
pipelineVariables:
FOO: bar
```
use in your pipeline
* run the jx variables step
* source the .jx/variables.sh file
* use as ${FOO}
> feat: global pipeline variables

- .lighthouse/jenkins-x/release.yaml
- charts/jxboot-helmfile-resources/Makefile
> fix: try release to the bucket

- charts/jxboot-helmfile-resources/Makefile
> fix: switch to the jx3 repo

- charts/jxboot-helmfile-resources/requirements.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcactivities-rb.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcactivities-role.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcactivities-sa.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcpods-rb.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcpods-role.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcpods-sa.yaml
- charts/jxboot-helmfile-resources/values.yaml
and remove the old v2 chart dependency
Signed-off-by: jenkins-x-test-bot <jenkins-x@googlegroups.com>
> fix: add new GC jobs

- charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
Signed-off-by: jenkins-x-test-bot <jenkins-x@googlegroups.com>
> fix: use correct command line

- charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
> fix: flags

- charts/jxboot-helmfile-resources/templates/release-gpg-secret.yaml
- charts/jxboot-helmfile-resources/values.yaml
> fix: disable gpg secret by default

- charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
> fix: allow annotations for gc job pods again

- charts/jxboot-helmfile-resources/templates/upgrade-cj.yaml
- charts/jxboot-helmfile-resources/values.yaml
> fix: add better upgrade CronJob

- charts/jxboot-helmfile-resources/templates/upgrade-cj.yaml
- charts/jxboot-helmfile-resources/values.yaml
> fix: add auto merge flag

- charts/jxboot-helmfile-resources/templates/upgrade-cj.yaml
- charts/jxboot-helmfile-resources/values.yaml
> fix: latest updatebot and avoid env var

- charts/jxboot-helmfile-resources/values.yaml
> chore: upgrade updatebot

- charts/jxboot-helmfile-resources/values.yaml
> fix: upgrade updatebot

- charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
Closes #351
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
> fix: set startingDeadlineSeconds to jobs not scheduling

- charts/jxboot-helmfile-resources/templates/jx-gcactivities-role.yaml
- charts/jxboot-helmfile-resources/values.yaml
> fix: give list and delete access to lhjobs

- charts/jxboot-helmfile-resources/values.yaml
See https://github.com/GoogleContainerTools/kaniko/issues/1305
Signed-off-by: Mihai Plasoianu <mihai@plasoianu.de>
> chore: improve Kaniko build time

- charts/jxboot-helmfile-resources/values.yaml
Signed-off-by: Mihai Plasoianu <mihai@plasoianu.de>
> chore: skip unused Dockerfile stages

- charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
- charts/jxboot-helmfile-resources/values.yaml
> feat: allow end users to pass extra args to gc cronjob

- charts/jxboot-helmfile-resources/values.yaml
> chore: update jx version to 3.2.217

- charts/jxboot-helmfile-resources/values.yaml
> fix: upgrade jx version to fix gc jobs

- charts/jxboot-helmfile-resources/templates/jx-gcjobs-cronjob.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcjobs-rb.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcjobs-role.yaml
- charts/jxboot-helmfile-resources/templates/jx-gcjobs-sa.yaml
- charts/jxboot-helmfile-resources/values.yaml
It should fix gc jobs permissions error
> fix: change gc jobs RBAC roles

- charts/jxboot-helmfile-resources/templates/environments.yaml
The repository bucket location is not available now. In the future other locations might be added.
I also added quoting, just for the sake of safety.
> fix: Make all storage locations available in env

- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
- OWNERS
- charts/jxboot-helmfile-resources/values.yaml
> fix: remove resource request from step template

- charts/jxboot-helmfile-resources/values.yaml
- fix typo as per in SVC `externalName`
> fix: typo in values.yml for externalname -> externalName
